#!/bin/sh

printf "Running detekt...\r"

OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew :resources-plugin:detekt :resources-library:detekt -PautoCorrect=true > "$OUTPUT"
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  cat "$OUTPUT"
  echo "*********************************************"
  echo "* Please fix the issues above and try again *"
  echo "*********************************************"
fi

rm "$OUTPUT"
exit $EXIT_CODE
